require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Configuration::CsvImportsController do

  # This should return the minimal set of attributes required to create a valid
  # Configuration::CsvImport. As you add validations to Configuration::CsvImport, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Configuration::CsvImportsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all configuration_csv_imports as @configuration_csv_imports" do
      csv_import = Configuration::CsvImport.create! valid_attributes
      get :index, {}, valid_session
      assigns(:configuration_csv_imports).should eq([csv_import])
    end
  end

  describe "GET show" do
    it "assigns the requested configuration_csv_import as @configuration_csv_import" do
      csv_import = Configuration::CsvImport.create! valid_attributes
      get :show, {:id => csv_import.to_param}, valid_session
      assigns(:configuration_csv_import).should eq(csv_import)
    end
  end

  describe "GET new" do
    it "assigns a new configuration_csv_import as @configuration_csv_import" do
      get :new, {}, valid_session
      assigns(:configuration_csv_import).should be_a_new(Configuration::CsvImport)
    end
  end

  describe "GET edit" do
    it "assigns the requested configuration_csv_import as @configuration_csv_import" do
      csv_import = Configuration::CsvImport.create! valid_attributes
      get :edit, {:id => csv_import.to_param}, valid_session
      assigns(:configuration_csv_import).should eq(csv_import)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Configuration::CsvImport" do
        expect {
          post :create, {:configuration_csv_import => valid_attributes}, valid_session
        }.to change(Configuration::CsvImport, :count).by(1)
      end

      it "assigns a newly created configuration_csv_import as @configuration_csv_import" do
        post :create, {:configuration_csv_import => valid_attributes}, valid_session
        assigns(:configuration_csv_import).should be_a(Configuration::CsvImport)
        assigns(:configuration_csv_import).should be_persisted
      end

      it "redirects to the created configuration_csv_import" do
        post :create, {:configuration_csv_import => valid_attributes}, valid_session
        response.should redirect_to(Configuration::CsvImport.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved configuration_csv_import as @configuration_csv_import" do
        # Trigger the behavior that occurs when invalid params are submitted
        Configuration::CsvImport.any_instance.stub(:save).and_return(false)
        post :create, {:configuration_csv_import => {  }}, valid_session
        assigns(:configuration_csv_import).should be_a_new(Configuration::CsvImport)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Configuration::CsvImport.any_instance.stub(:save).and_return(false)
        post :create, {:configuration_csv_import => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested configuration_csv_import" do
        csv_import = Configuration::CsvImport.create! valid_attributes
        # Assuming there are no other configuration_csv_imports in the database, this
        # specifies that the Configuration::CsvImport created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Configuration::CsvImport.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => csv_import.to_param, :configuration_csv_import => { "these" => "params" }}, valid_session
      end

      it "assigns the requested configuration_csv_import as @configuration_csv_import" do
        csv_import = Configuration::CsvImport.create! valid_attributes
        put :update, {:id => csv_import.to_param, :configuration_csv_import => valid_attributes}, valid_session
        assigns(:configuration_csv_import).should eq(csv_import)
      end

      it "redirects to the configuration_csv_import" do
        csv_import = Configuration::CsvImport.create! valid_attributes
        put :update, {:id => csv_import.to_param, :configuration_csv_import => valid_attributes}, valid_session
        response.should redirect_to(csv_import)
      end
    end

    describe "with invalid params" do
      it "assigns the configuration_csv_import as @configuration_csv_import" do
        csv_import = Configuration::CsvImport.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Configuration::CsvImport.any_instance.stub(:save).and_return(false)
        put :update, {:id => csv_import.to_param, :configuration_csv_import => {  }}, valid_session
        assigns(:configuration_csv_import).should eq(csv_import)
      end

      it "re-renders the 'edit' template" do
        csv_import = Configuration::CsvImport.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Configuration::CsvImport.any_instance.stub(:save).and_return(false)
        put :update, {:id => csv_import.to_param, :configuration_csv_import => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested configuration_csv_import" do
      csv_import = Configuration::CsvImport.create! valid_attributes
      expect {
        delete :destroy, {:id => csv_import.to_param}, valid_session
      }.to change(Configuration::CsvImport, :count).by(-1)
    end

    it "redirects to the configuration_csv_imports list" do
      csv_import = Configuration::CsvImport.create! valid_attributes
      delete :destroy, {:id => csv_import.to_param}, valid_session
      response.should redirect_to(configuration_csv_imports_url)
    end
  end

end
