require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Configuration::LeaveTypesController do

  # This should return the minimal set of attributes required to create a valid
  # Configuration::LeaveType. As you add validations to Configuration::LeaveType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Configuration::LeaveTypesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all configuration_leave_types as @configuration_leave_types" do
      leave_type = Configuration::LeaveType.create! valid_attributes
      get :index, {}, valid_session
      assigns(:configuration_leave_types).should eq([leave_type])
    end
  end

  describe "GET show" do
    it "assigns the requested configuration_leave_type as @configuration_leave_type" do
      leave_type = Configuration::LeaveType.create! valid_attributes
      get :show, {:id => leave_type.to_param}, valid_session
      assigns(:configuration_leave_type).should eq(leave_type)
    end
  end

  describe "GET new" do
    it "assigns a new configuration_leave_type as @configuration_leave_type" do
      get :new, {}, valid_session
      assigns(:configuration_leave_type).should be_a_new(Configuration::LeaveType)
    end
  end

  describe "GET edit" do
    it "assigns the requested configuration_leave_type as @configuration_leave_type" do
      leave_type = Configuration::LeaveType.create! valid_attributes
      get :edit, {:id => leave_type.to_param}, valid_session
      assigns(:configuration_leave_type).should eq(leave_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Configuration::LeaveType" do
        expect {
          post :create, {:configuration_leave_type => valid_attributes}, valid_session
        }.to change(Configuration::LeaveType, :count).by(1)
      end

      it "assigns a newly created configuration_leave_type as @configuration_leave_type" do
        post :create, {:configuration_leave_type => valid_attributes}, valid_session
        assigns(:configuration_leave_type).should be_a(Configuration::LeaveType)
        assigns(:configuration_leave_type).should be_persisted
      end

      it "redirects to the created configuration_leave_type" do
        post :create, {:configuration_leave_type => valid_attributes}, valid_session
        response.should redirect_to(Configuration::LeaveType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved configuration_leave_type as @configuration_leave_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        Configuration::LeaveType.any_instance.stub(:save).and_return(false)
        post :create, {:configuration_leave_type => {  }}, valid_session
        assigns(:configuration_leave_type).should be_a_new(Configuration::LeaveType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Configuration::LeaveType.any_instance.stub(:save).and_return(false)
        post :create, {:configuration_leave_type => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested configuration_leave_type" do
        leave_type = Configuration::LeaveType.create! valid_attributes
        # Assuming there are no other configuration_leave_types in the database, this
        # specifies that the Configuration::LeaveType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Configuration::LeaveType.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => leave_type.to_param, :configuration_leave_type => { "these" => "params" }}, valid_session
      end

      it "assigns the requested configuration_leave_type as @configuration_leave_type" do
        leave_type = Configuration::LeaveType.create! valid_attributes
        put :update, {:id => leave_type.to_param, :configuration_leave_type => valid_attributes}, valid_session
        assigns(:configuration_leave_type).should eq(leave_type)
      end

      it "redirects to the configuration_leave_type" do
        leave_type = Configuration::LeaveType.create! valid_attributes
        put :update, {:id => leave_type.to_param, :configuration_leave_type => valid_attributes}, valid_session
        response.should redirect_to(leave_type)
      end
    end

    describe "with invalid params" do
      it "assigns the configuration_leave_type as @configuration_leave_type" do
        leave_type = Configuration::LeaveType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Configuration::LeaveType.any_instance.stub(:save).and_return(false)
        put :update, {:id => leave_type.to_param, :configuration_leave_type => {  }}, valid_session
        assigns(:configuration_leave_type).should eq(leave_type)
      end

      it "re-renders the 'edit' template" do
        leave_type = Configuration::LeaveType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Configuration::LeaveType.any_instance.stub(:save).and_return(false)
        put :update, {:id => leave_type.to_param, :configuration_leave_type => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested configuration_leave_type" do
      leave_type = Configuration::LeaveType.create! valid_attributes
      expect {
        delete :destroy, {:id => leave_type.to_param}, valid_session
      }.to change(Configuration::LeaveType, :count).by(-1)
    end

    it "redirects to the configuration_leave_types list" do
      leave_type = Configuration::LeaveType.create! valid_attributes
      delete :destroy, {:id => leave_type.to_param}, valid_session
      response.should redirect_to(configuration_leave_types_url)
    end
  end

end
