require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Configuration::LeavesController do

  # This should return the minimal set of attributes required to create a valid
  # Configuration::Leafe. As you add validations to Configuration::Leafe, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Configuration::LeavesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all configuration_leaves as @configuration_leaves" do
      leafe = Configuration::Leafe.create! valid_attributes
      get :index, {}, valid_session
      assigns(:configuration_leaves).should eq([leafe])
    end
  end

  describe "GET show" do
    it "assigns the requested configuration_leafe as @configuration_leafe" do
      leafe = Configuration::Leafe.create! valid_attributes
      get :show, {:id => leafe.to_param}, valid_session
      assigns(:configuration_leafe).should eq(leafe)
    end
  end

  describe "GET new" do
    it "assigns a new configuration_leafe as @configuration_leafe" do
      get :new, {}, valid_session
      assigns(:configuration_leafe).should be_a_new(Configuration::Leafe)
    end
  end

  describe "GET edit" do
    it "assigns the requested configuration_leafe as @configuration_leafe" do
      leafe = Configuration::Leafe.create! valid_attributes
      get :edit, {:id => leafe.to_param}, valid_session
      assigns(:configuration_leafe).should eq(leafe)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Configuration::Leafe" do
        expect {
          post :create, {:configuration_leafe => valid_attributes}, valid_session
        }.to change(Configuration::Leafe, :count).by(1)
      end

      it "assigns a newly created configuration_leafe as @configuration_leafe" do
        post :create, {:configuration_leafe => valid_attributes}, valid_session
        assigns(:configuration_leafe).should be_a(Configuration::Leafe)
        assigns(:configuration_leafe).should be_persisted
      end

      it "redirects to the created configuration_leafe" do
        post :create, {:configuration_leafe => valid_attributes}, valid_session
        response.should redirect_to(Configuration::Leafe.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved configuration_leafe as @configuration_leafe" do
        # Trigger the behavior that occurs when invalid params are submitted
        Configuration::Leafe.any_instance.stub(:save).and_return(false)
        post :create, {:configuration_leafe => {  }}, valid_session
        assigns(:configuration_leafe).should be_a_new(Configuration::Leafe)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Configuration::Leafe.any_instance.stub(:save).and_return(false)
        post :create, {:configuration_leafe => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested configuration_leafe" do
        leafe = Configuration::Leafe.create! valid_attributes
        # Assuming there are no other configuration_leaves in the database, this
        # specifies that the Configuration::Leafe created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Configuration::Leafe.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => leafe.to_param, :configuration_leafe => { "these" => "params" }}, valid_session
      end

      it "assigns the requested configuration_leafe as @configuration_leafe" do
        leafe = Configuration::Leafe.create! valid_attributes
        put :update, {:id => leafe.to_param, :configuration_leafe => valid_attributes}, valid_session
        assigns(:configuration_leafe).should eq(leafe)
      end

      it "redirects to the configuration_leafe" do
        leafe = Configuration::Leafe.create! valid_attributes
        put :update, {:id => leafe.to_param, :configuration_leafe => valid_attributes}, valid_session
        response.should redirect_to(leafe)
      end
    end

    describe "with invalid params" do
      it "assigns the configuration_leafe as @configuration_leafe" do
        leafe = Configuration::Leafe.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Configuration::Leafe.any_instance.stub(:save).and_return(false)
        put :update, {:id => leafe.to_param, :configuration_leafe => {  }}, valid_session
        assigns(:configuration_leafe).should eq(leafe)
      end

      it "re-renders the 'edit' template" do
        leafe = Configuration::Leafe.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Configuration::Leafe.any_instance.stub(:save).and_return(false)
        put :update, {:id => leafe.to_param, :configuration_leafe => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested configuration_leafe" do
      leafe = Configuration::Leafe.create! valid_attributes
      expect {
        delete :destroy, {:id => leafe.to_param}, valid_session
      }.to change(Configuration::Leafe, :count).by(-1)
    end

    it "redirects to the configuration_leaves list" do
      leafe = Configuration::Leafe.create! valid_attributes
      delete :destroy, {:id => leafe.to_param}, valid_session
      response.should redirect_to(configuration_leaves_url)
    end
  end

end
