require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UserManagement::RolesController do

  # This should return the minimal set of attributes required to create a valid
  # UserManagement::Role. As you add validations to UserManagement::Role, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UserManagement::RolesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all user_management_roles as @user_management_roles" do
      role = UserManagement::Role.create! valid_attributes
      get :index, {}, valid_session
      assigns(:user_management_roles).should eq([role])
    end
  end

  describe "GET show" do
    it "assigns the requested user_management_role as @user_management_role" do
      role = UserManagement::Role.create! valid_attributes
      get :show, {:id => role.to_param}, valid_session
      assigns(:user_management_role).should eq(role)
    end
  end

  describe "GET new" do
    it "assigns a new user_management_role as @user_management_role" do
      get :new, {}, valid_session
      assigns(:user_management_role).should be_a_new(UserManagement::Role)
    end
  end

  describe "GET edit" do
    it "assigns the requested user_management_role as @user_management_role" do
      role = UserManagement::Role.create! valid_attributes
      get :edit, {:id => role.to_param}, valid_session
      assigns(:user_management_role).should eq(role)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new UserManagement::Role" do
        expect {
          post :create, {:user_management_role => valid_attributes}, valid_session
        }.to change(UserManagement::Role, :count).by(1)
      end

      it "assigns a newly created user_management_role as @user_management_role" do
        post :create, {:user_management_role => valid_attributes}, valid_session
        assigns(:user_management_role).should be_a(UserManagement::Role)
        assigns(:user_management_role).should be_persisted
      end

      it "redirects to the created user_management_role" do
        post :create, {:user_management_role => valid_attributes}, valid_session
        response.should redirect_to(UserManagement::Role.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved user_management_role as @user_management_role" do
        # Trigger the behavior that occurs when invalid params are submitted
        UserManagement::Role.any_instance.stub(:save).and_return(false)
        post :create, {:user_management_role => {  }}, valid_session
        assigns(:user_management_role).should be_a_new(UserManagement::Role)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        UserManagement::Role.any_instance.stub(:save).and_return(false)
        post :create, {:user_management_role => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested user_management_role" do
        role = UserManagement::Role.create! valid_attributes
        # Assuming there are no other user_management_roles in the database, this
        # specifies that the UserManagement::Role created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        UserManagement::Role.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => role.to_param, :user_management_role => { "these" => "params" }}, valid_session
      end

      it "assigns the requested user_management_role as @user_management_role" do
        role = UserManagement::Role.create! valid_attributes
        put :update, {:id => role.to_param, :user_management_role => valid_attributes}, valid_session
        assigns(:user_management_role).should eq(role)
      end

      it "redirects to the user_management_role" do
        role = UserManagement::Role.create! valid_attributes
        put :update, {:id => role.to_param, :user_management_role => valid_attributes}, valid_session
        response.should redirect_to(role)
      end
    end

    describe "with invalid params" do
      it "assigns the user_management_role as @user_management_role" do
        role = UserManagement::Role.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UserManagement::Role.any_instance.stub(:save).and_return(false)
        put :update, {:id => role.to_param, :user_management_role => {  }}, valid_session
        assigns(:user_management_role).should eq(role)
      end

      it "re-renders the 'edit' template" do
        role = UserManagement::Role.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UserManagement::Role.any_instance.stub(:save).and_return(false)
        put :update, {:id => role.to_param, :user_management_role => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested user_management_role" do
      role = UserManagement::Role.create! valid_attributes
      expect {
        delete :destroy, {:id => role.to_param}, valid_session
      }.to change(UserManagement::Role, :count).by(-1)
    end

    it "redirects to the user_management_roles list" do
      role = UserManagement::Role.create! valid_attributes
      delete :destroy, {:id => role.to_param}, valid_session
      response.should redirect_to(user_management_roles_url)
    end
  end

end
