require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Organization::OrganizationGeneralInformationsController do

  # This should return the minimal set of attributes required to create a valid
  # Organization::OrganizationGeneralInformation. As you add validations to Organization::OrganizationGeneralInformation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Organization::OrganizationGeneralInformationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all organization_organization_general_informations as @organization_organization_general_informations" do
      organization_general_information = Organization::OrganizationGeneralInformation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:organization_organization_general_informations).should eq([organization_general_information])
    end
  end

  describe "GET show" do
    it "assigns the requested organization_organization_general_information as @organization_organization_general_information" do
      organization_general_information = Organization::OrganizationGeneralInformation.create! valid_attributes
      get :show, {:id => organization_general_information.to_param}, valid_session
      assigns(:organization_organization_general_information).should eq(organization_general_information)
    end
  end

  describe "GET new" do
    it "assigns a new organization_organization_general_information as @organization_organization_general_information" do
      get :new, {}, valid_session
      assigns(:organization_organization_general_information).should be_a_new(Organization::OrganizationGeneralInformation)
    end
  end

  describe "GET edit" do
    it "assigns the requested organization_organization_general_information as @organization_organization_general_information" do
      organization_general_information = Organization::OrganizationGeneralInformation.create! valid_attributes
      get :edit, {:id => organization_general_information.to_param}, valid_session
      assigns(:organization_organization_general_information).should eq(organization_general_information)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Organization::OrganizationGeneralInformation" do
        expect {
          post :create, {:organization_organization_general_information => valid_attributes}, valid_session
        }.to change(Organization::OrganizationGeneralInformation, :count).by(1)
      end

      it "assigns a newly created organization_organization_general_information as @organization_organization_general_information" do
        post :create, {:organization_organization_general_information => valid_attributes}, valid_session
        assigns(:organization_organization_general_information).should be_a(Organization::OrganizationGeneralInformation)
        assigns(:organization_organization_general_information).should be_persisted
      end

      it "redirects to the created organization_organization_general_information" do
        post :create, {:organization_organization_general_information => valid_attributes}, valid_session
        response.should redirect_to(Organization::OrganizationGeneralInformation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved organization_organization_general_information as @organization_organization_general_information" do
        # Trigger the behavior that occurs when invalid params are submitted
        Organization::OrganizationGeneralInformation.any_instance.stub(:save).and_return(false)
        post :create, {:organization_organization_general_information => { "name" => "invalid value" }}, valid_session
        assigns(:organization_organization_general_information).should be_a_new(Organization::OrganizationGeneralInformation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Organization::OrganizationGeneralInformation.any_instance.stub(:save).and_return(false)
        post :create, {:organization_organization_general_information => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested organization_organization_general_information" do
        organization_general_information = Organization::OrganizationGeneralInformation.create! valid_attributes
        # Assuming there are no other organization_organization_general_informations in the database, this
        # specifies that the Organization::OrganizationGeneralInformation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Organization::OrganizationGeneralInformation.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => organization_general_information.to_param, :organization_organization_general_information => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested organization_organization_general_information as @organization_organization_general_information" do
        organization_general_information = Organization::OrganizationGeneralInformation.create! valid_attributes
        put :update, {:id => organization_general_information.to_param, :organization_organization_general_information => valid_attributes}, valid_session
        assigns(:organization_organization_general_information).should eq(organization_general_information)
      end

      it "redirects to the organization_organization_general_information" do
        organization_general_information = Organization::OrganizationGeneralInformation.create! valid_attributes
        put :update, {:id => organization_general_information.to_param, :organization_organization_general_information => valid_attributes}, valid_session
        response.should redirect_to(organization_general_information)
      end
    end

    describe "with invalid params" do
      it "assigns the organization_organization_general_information as @organization_organization_general_information" do
        organization_general_information = Organization::OrganizationGeneralInformation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Organization::OrganizationGeneralInformation.any_instance.stub(:save).and_return(false)
        put :update, {:id => organization_general_information.to_param, :organization_organization_general_information => { "name" => "invalid value" }}, valid_session
        assigns(:organization_organization_general_information).should eq(organization_general_information)
      end

      it "re-renders the 'edit' template" do
        organization_general_information = Organization::OrganizationGeneralInformation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Organization::OrganizationGeneralInformation.any_instance.stub(:save).and_return(false)
        put :update, {:id => organization_general_information.to_param, :organization_organization_general_information => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested organization_organization_general_information" do
      organization_general_information = Organization::OrganizationGeneralInformation.create! valid_attributes
      expect {
        delete :destroy, {:id => organization_general_information.to_param}, valid_session
      }.to change(Organization::OrganizationGeneralInformation, :count).by(-1)
    end

    it "redirects to the organization_organization_general_informations list" do
      organization_general_information = Organization::OrganizationGeneralInformation.create! valid_attributes
      delete :destroy, {:id => organization_general_information.to_param}, valid_session
      response.should redirect_to(organization_organization_general_informations_url)
    end
  end

end
