require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Job::CategoriesController do

  # This should return the minimal set of attributes required to create a valid
  # Job::Category. As you add validations to Job::Category, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Job::CategoriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all job_categories as @job_categories" do
      category = Job::Category.create! valid_attributes
      get :index, {}, valid_session
      assigns(:job_categories).should eq([category])
    end
  end

  describe "GET show" do
    it "assigns the requested job_category as @job_category" do
      category = Job::Category.create! valid_attributes
      get :show, {:id => category.to_param}, valid_session
      assigns(:job_category).should eq(category)
    end
  end

  describe "GET new" do
    it "assigns a new job_category as @job_category" do
      get :new, {}, valid_session
      assigns(:job_category).should be_a_new(Job::Category)
    end
  end

  describe "GET edit" do
    it "assigns the requested job_category as @job_category" do
      category = Job::Category.create! valid_attributes
      get :edit, {:id => category.to_param}, valid_session
      assigns(:job_category).should eq(category)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Job::Category" do
        expect {
          post :create, {:job_category => valid_attributes}, valid_session
        }.to change(Job::Category, :count).by(1)
      end

      it "assigns a newly created job_category as @job_category" do
        post :create, {:job_category => valid_attributes}, valid_session
        assigns(:job_category).should be_a(Job::Category)
        assigns(:job_category).should be_persisted
      end

      it "redirects to the created job_category" do
        post :create, {:job_category => valid_attributes}, valid_session
        response.should redirect_to(Job::Category.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved job_category as @job_category" do
        # Trigger the behavior that occurs when invalid params are submitted
        Job::Category.any_instance.stub(:save).and_return(false)
        post :create, {:job_category => {  }}, valid_session
        assigns(:job_category).should be_a_new(Job::Category)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Job::Category.any_instance.stub(:save).and_return(false)
        post :create, {:job_category => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested job_category" do
        category = Job::Category.create! valid_attributes
        # Assuming there are no other job_categories in the database, this
        # specifies that the Job::Category created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Job::Category.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => category.to_param, :job_category => { "these" => "params" }}, valid_session
      end

      it "assigns the requested job_category as @job_category" do
        category = Job::Category.create! valid_attributes
        put :update, {:id => category.to_param, :job_category => valid_attributes}, valid_session
        assigns(:job_category).should eq(category)
      end

      it "redirects to the job_category" do
        category = Job::Category.create! valid_attributes
        put :update, {:id => category.to_param, :job_category => valid_attributes}, valid_session
        response.should redirect_to(category)
      end
    end

    describe "with invalid params" do
      it "assigns the job_category as @job_category" do
        category = Job::Category.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Job::Category.any_instance.stub(:save).and_return(false)
        put :update, {:id => category.to_param, :job_category => {  }}, valid_session
        assigns(:job_category).should eq(category)
      end

      it "re-renders the 'edit' template" do
        category = Job::Category.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Job::Category.any_instance.stub(:save).and_return(false)
        put :update, {:id => category.to_param, :job_category => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested job_category" do
      category = Job::Category.create! valid_attributes
      expect {
        delete :destroy, {:id => category.to_param}, valid_session
      }.to change(Job::Category, :count).by(-1)
    end

    it "redirects to the job_categories list" do
      category = Job::Category.create! valid_attributes
      delete :destroy, {:id => category.to_param}, valid_session
      response.should redirect_to(job_categories_url)
    end
  end

end
