require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Job::SalaryComponentsController do

  # This should return the minimal set of attributes required to create a valid
  # Job::SalaryComponent. As you add validations to Job::SalaryComponent, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Job::SalaryComponentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all job_salary_components as @job_salary_components" do
      salary_component = Job::SalaryComponent.create! valid_attributes
      get :index, {}, valid_session
      assigns(:job_salary_components).should eq([salary_component])
    end
  end

  describe "GET show" do
    it "assigns the requested job_salary_component as @job_salary_component" do
      salary_component = Job::SalaryComponent.create! valid_attributes
      get :show, {:id => salary_component.to_param}, valid_session
      assigns(:job_salary_component).should eq(salary_component)
    end
  end

  describe "GET new" do
    it "assigns a new job_salary_component as @job_salary_component" do
      get :new, {}, valid_session
      assigns(:job_salary_component).should be_a_new(Job::SalaryComponent)
    end
  end

  describe "GET edit" do
    it "assigns the requested job_salary_component as @job_salary_component" do
      salary_component = Job::SalaryComponent.create! valid_attributes
      get :edit, {:id => salary_component.to_param}, valid_session
      assigns(:job_salary_component).should eq(salary_component)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Job::SalaryComponent" do
        expect {
          post :create, {:job_salary_component => valid_attributes}, valid_session
        }.to change(Job::SalaryComponent, :count).by(1)
      end

      it "assigns a newly created job_salary_component as @job_salary_component" do
        post :create, {:job_salary_component => valid_attributes}, valid_session
        assigns(:job_salary_component).should be_a(Job::SalaryComponent)
        assigns(:job_salary_component).should be_persisted
      end

      it "redirects to the created job_salary_component" do
        post :create, {:job_salary_component => valid_attributes}, valid_session
        response.should redirect_to(Job::SalaryComponent.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved job_salary_component as @job_salary_component" do
        # Trigger the behavior that occurs when invalid params are submitted
        Job::SalaryComponent.any_instance.stub(:save).and_return(false)
        post :create, {:job_salary_component => {  }}, valid_session
        assigns(:job_salary_component).should be_a_new(Job::SalaryComponent)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Job::SalaryComponent.any_instance.stub(:save).and_return(false)
        post :create, {:job_salary_component => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested job_salary_component" do
        salary_component = Job::SalaryComponent.create! valid_attributes
        # Assuming there are no other job_salary_components in the database, this
        # specifies that the Job::SalaryComponent created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Job::SalaryComponent.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => salary_component.to_param, :job_salary_component => { "these" => "params" }}, valid_session
      end

      it "assigns the requested job_salary_component as @job_salary_component" do
        salary_component = Job::SalaryComponent.create! valid_attributes
        put :update, {:id => salary_component.to_param, :job_salary_component => valid_attributes}, valid_session
        assigns(:job_salary_component).should eq(salary_component)
      end

      it "redirects to the job_salary_component" do
        salary_component = Job::SalaryComponent.create! valid_attributes
        put :update, {:id => salary_component.to_param, :job_salary_component => valid_attributes}, valid_session
        response.should redirect_to(salary_component)
      end
    end

    describe "with invalid params" do
      it "assigns the job_salary_component as @job_salary_component" do
        salary_component = Job::SalaryComponent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Job::SalaryComponent.any_instance.stub(:save).and_return(false)
        put :update, {:id => salary_component.to_param, :job_salary_component => {  }}, valid_session
        assigns(:job_salary_component).should eq(salary_component)
      end

      it "re-renders the 'edit' template" do
        salary_component = Job::SalaryComponent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Job::SalaryComponent.any_instance.stub(:save).and_return(false)
        put :update, {:id => salary_component.to_param, :job_salary_component => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested job_salary_component" do
      salary_component = Job::SalaryComponent.create! valid_attributes
      expect {
        delete :destroy, {:id => salary_component.to_param}, valid_session
      }.to change(Job::SalaryComponent, :count).by(-1)
    end

    it "redirects to the job_salary_components list" do
      salary_component = Job::SalaryComponent.create! valid_attributes
      delete :destroy, {:id => salary_component.to_param}, valid_session
      response.should redirect_to(job_salary_components_url)
    end
  end

end
