require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Qualifications::EducationsController do

  # This should return the minimal set of attributes required to create a valid
  # Qualifications::Education. As you add validations to Qualifications::Education, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Qualifications::EducationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all qualifications_educations as @qualifications_educations" do
      education = Qualifications::Education.create! valid_attributes
      get :index, {}, valid_session
      assigns(:qualifications_educations).should eq([education])
    end
  end

  describe "GET show" do
    it "assigns the requested qualifications_education as @qualifications_education" do
      education = Qualifications::Education.create! valid_attributes
      get :show, {:id => education.to_param}, valid_session
      assigns(:qualifications_education).should eq(education)
    end
  end

  describe "GET new" do
    it "assigns a new qualifications_education as @qualifications_education" do
      get :new, {}, valid_session
      assigns(:qualifications_education).should be_a_new(Qualifications::Education)
    end
  end

  describe "GET edit" do
    it "assigns the requested qualifications_education as @qualifications_education" do
      education = Qualifications::Education.create! valid_attributes
      get :edit, {:id => education.to_param}, valid_session
      assigns(:qualifications_education).should eq(education)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Qualifications::Education" do
        expect {
          post :create, {:qualifications_education => valid_attributes}, valid_session
        }.to change(Qualifications::Education, :count).by(1)
      end

      it "assigns a newly created qualifications_education as @qualifications_education" do
        post :create, {:qualifications_education => valid_attributes}, valid_session
        assigns(:qualifications_education).should be_a(Qualifications::Education)
        assigns(:qualifications_education).should be_persisted
      end

      it "redirects to the created qualifications_education" do
        post :create, {:qualifications_education => valid_attributes}, valid_session
        response.should redirect_to(Qualifications::Education.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved qualifications_education as @qualifications_education" do
        # Trigger the behavior that occurs when invalid params are submitted
        Qualifications::Education.any_instance.stub(:save).and_return(false)
        post :create, {:qualifications_education => {  }}, valid_session
        assigns(:qualifications_education).should be_a_new(Qualifications::Education)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Qualifications::Education.any_instance.stub(:save).and_return(false)
        post :create, {:qualifications_education => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested qualifications_education" do
        education = Qualifications::Education.create! valid_attributes
        # Assuming there are no other qualifications_educations in the database, this
        # specifies that the Qualifications::Education created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Qualifications::Education.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => education.to_param, :qualifications_education => { "these" => "params" }}, valid_session
      end

      it "assigns the requested qualifications_education as @qualifications_education" do
        education = Qualifications::Education.create! valid_attributes
        put :update, {:id => education.to_param, :qualifications_education => valid_attributes}, valid_session
        assigns(:qualifications_education).should eq(education)
      end

      it "redirects to the qualifications_education" do
        education = Qualifications::Education.create! valid_attributes
        put :update, {:id => education.to_param, :qualifications_education => valid_attributes}, valid_session
        response.should redirect_to(education)
      end
    end

    describe "with invalid params" do
      it "assigns the qualifications_education as @qualifications_education" do
        education = Qualifications::Education.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Qualifications::Education.any_instance.stub(:save).and_return(false)
        put :update, {:id => education.to_param, :qualifications_education => {  }}, valid_session
        assigns(:qualifications_education).should eq(education)
      end

      it "re-renders the 'edit' template" do
        education = Qualifications::Education.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Qualifications::Education.any_instance.stub(:save).and_return(false)
        put :update, {:id => education.to_param, :qualifications_education => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested qualifications_education" do
      education = Qualifications::Education.create! valid_attributes
      expect {
        delete :destroy, {:id => education.to_param}, valid_session
      }.to change(Qualifications::Education, :count).by(-1)
    end

    it "redirects to the qualifications_educations list" do
      education = Qualifications::Education.create! valid_attributes
      delete :destroy, {:id => education.to_param}, valid_session
      response.should redirect_to(qualifications_educations_url)
    end
  end

end
