require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Qualifications::SkillsController do

  # This should return the minimal set of attributes required to create a valid
  # Qualifications::Skill. As you add validations to Qualifications::Skill, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Qualifications::SkillsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all qualifications_skills as @qualifications_skills" do
      skill = Qualifications::Skill.create! valid_attributes
      get :index, {}, valid_session
      assigns(:qualifications_skills).should eq([skill])
    end
  end

  describe "GET show" do
    it "assigns the requested qualifications_skill as @qualifications_skill" do
      skill = Qualifications::Skill.create! valid_attributes
      get :show, {:id => skill.to_param}, valid_session
      assigns(:qualifications_skill).should eq(skill)
    end
  end

  describe "GET new" do
    it "assigns a new qualifications_skill as @qualifications_skill" do
      get :new, {}, valid_session
      assigns(:qualifications_skill).should be_a_new(Qualifications::Skill)
    end
  end

  describe "GET edit" do
    it "assigns the requested qualifications_skill as @qualifications_skill" do
      skill = Qualifications::Skill.create! valid_attributes
      get :edit, {:id => skill.to_param}, valid_session
      assigns(:qualifications_skill).should eq(skill)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Qualifications::Skill" do
        expect {
          post :create, {:qualifications_skill => valid_attributes}, valid_session
        }.to change(Qualifications::Skill, :count).by(1)
      end

      it "assigns a newly created qualifications_skill as @qualifications_skill" do
        post :create, {:qualifications_skill => valid_attributes}, valid_session
        assigns(:qualifications_skill).should be_a(Qualifications::Skill)
        assigns(:qualifications_skill).should be_persisted
      end

      it "redirects to the created qualifications_skill" do
        post :create, {:qualifications_skill => valid_attributes}, valid_session
        response.should redirect_to(Qualifications::Skill.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved qualifications_skill as @qualifications_skill" do
        # Trigger the behavior that occurs when invalid params are submitted
        Qualifications::Skill.any_instance.stub(:save).and_return(false)
        post :create, {:qualifications_skill => { "name" => "invalid value" }}, valid_session
        assigns(:qualifications_skill).should be_a_new(Qualifications::Skill)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Qualifications::Skill.any_instance.stub(:save).and_return(false)
        post :create, {:qualifications_skill => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested qualifications_skill" do
        skill = Qualifications::Skill.create! valid_attributes
        # Assuming there are no other qualifications_skills in the database, this
        # specifies that the Qualifications::Skill created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Qualifications::Skill.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => skill.to_param, :qualifications_skill => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested qualifications_skill as @qualifications_skill" do
        skill = Qualifications::Skill.create! valid_attributes
        put :update, {:id => skill.to_param, :qualifications_skill => valid_attributes}, valid_session
        assigns(:qualifications_skill).should eq(skill)
      end

      it "redirects to the qualifications_skill" do
        skill = Qualifications::Skill.create! valid_attributes
        put :update, {:id => skill.to_param, :qualifications_skill => valid_attributes}, valid_session
        response.should redirect_to(skill)
      end
    end

    describe "with invalid params" do
      it "assigns the qualifications_skill as @qualifications_skill" do
        skill = Qualifications::Skill.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Qualifications::Skill.any_instance.stub(:save).and_return(false)
        put :update, {:id => skill.to_param, :qualifications_skill => { "name" => "invalid value" }}, valid_session
        assigns(:qualifications_skill).should eq(skill)
      end

      it "re-renders the 'edit' template" do
        skill = Qualifications::Skill.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Qualifications::Skill.any_instance.stub(:save).and_return(false)
        put :update, {:id => skill.to_param, :qualifications_skill => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested qualifications_skill" do
      skill = Qualifications::Skill.create! valid_attributes
      expect {
        delete :destroy, {:id => skill.to_param}, valid_session
      }.to change(Qualifications::Skill, :count).by(-1)
    end

    it "redirects to the qualifications_skills list" do
      skill = Qualifications::Skill.create! valid_attributes
      delete :destroy, {:id => skill.to_param}, valid_session
      response.should redirect_to(qualifications_skills_url)
    end
  end

end
