require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Authentication::LdapConfigurationsController do

  # This should return the minimal set of attributes required to create a valid
  # Authentication::LdapConfiguration. As you add validations to Authentication::LdapConfiguration, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Authentication::LdapConfigurationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all authentication_ldap_configurations as @authentication_ldap_configurations" do
      ldap_configuration = Authentication::LdapConfiguration.create! valid_attributes
      get :index, {}, valid_session
      assigns(:authentication_ldap_configurations).should eq([ldap_configuration])
    end
  end

  describe "GET show" do
    it "assigns the requested authentication_ldap_configuration as @authentication_ldap_configuration" do
      ldap_configuration = Authentication::LdapConfiguration.create! valid_attributes
      get :show, {:id => ldap_configuration.to_param}, valid_session
      assigns(:authentication_ldap_configuration).should eq(ldap_configuration)
    end
  end

  describe "GET new" do
    it "assigns a new authentication_ldap_configuration as @authentication_ldap_configuration" do
      get :new, {}, valid_session
      assigns(:authentication_ldap_configuration).should be_a_new(Authentication::LdapConfiguration)
    end
  end

  describe "GET edit" do
    it "assigns the requested authentication_ldap_configuration as @authentication_ldap_configuration" do
      ldap_configuration = Authentication::LdapConfiguration.create! valid_attributes
      get :edit, {:id => ldap_configuration.to_param}, valid_session
      assigns(:authentication_ldap_configuration).should eq(ldap_configuration)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Authentication::LdapConfiguration" do
        expect {
          post :create, {:authentication_ldap_configuration => valid_attributes}, valid_session
        }.to change(Authentication::LdapConfiguration, :count).by(1)
      end

      it "assigns a newly created authentication_ldap_configuration as @authentication_ldap_configuration" do
        post :create, {:authentication_ldap_configuration => valid_attributes}, valid_session
        assigns(:authentication_ldap_configuration).should be_a(Authentication::LdapConfiguration)
        assigns(:authentication_ldap_configuration).should be_persisted
      end

      it "redirects to the created authentication_ldap_configuration" do
        post :create, {:authentication_ldap_configuration => valid_attributes}, valid_session
        response.should redirect_to(Authentication::LdapConfiguration.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved authentication_ldap_configuration as @authentication_ldap_configuration" do
        # Trigger the behavior that occurs when invalid params are submitted
        Authentication::LdapConfiguration.any_instance.stub(:save).and_return(false)
        post :create, {:authentication_ldap_configuration => {  }}, valid_session
        assigns(:authentication_ldap_configuration).should be_a_new(Authentication::LdapConfiguration)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Authentication::LdapConfiguration.any_instance.stub(:save).and_return(false)
        post :create, {:authentication_ldap_configuration => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested authentication_ldap_configuration" do
        ldap_configuration = Authentication::LdapConfiguration.create! valid_attributes
        # Assuming there are no other authentication_ldap_configurations in the database, this
        # specifies that the Authentication::LdapConfiguration created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Authentication::LdapConfiguration.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => ldap_configuration.to_param, :authentication_ldap_configuration => { "these" => "params" }}, valid_session
      end

      it "assigns the requested authentication_ldap_configuration as @authentication_ldap_configuration" do
        ldap_configuration = Authentication::LdapConfiguration.create! valid_attributes
        put :update, {:id => ldap_configuration.to_param, :authentication_ldap_configuration => valid_attributes}, valid_session
        assigns(:authentication_ldap_configuration).should eq(ldap_configuration)
      end

      it "redirects to the authentication_ldap_configuration" do
        ldap_configuration = Authentication::LdapConfiguration.create! valid_attributes
        put :update, {:id => ldap_configuration.to_param, :authentication_ldap_configuration => valid_attributes}, valid_session
        response.should redirect_to(ldap_configuration)
      end
    end

    describe "with invalid params" do
      it "assigns the authentication_ldap_configuration as @authentication_ldap_configuration" do
        ldap_configuration = Authentication::LdapConfiguration.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Authentication::LdapConfiguration.any_instance.stub(:save).and_return(false)
        put :update, {:id => ldap_configuration.to_param, :authentication_ldap_configuration => {  }}, valid_session
        assigns(:authentication_ldap_configuration).should eq(ldap_configuration)
      end

      it "re-renders the 'edit' template" do
        ldap_configuration = Authentication::LdapConfiguration.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Authentication::LdapConfiguration.any_instance.stub(:save).and_return(false)
        put :update, {:id => ldap_configuration.to_param, :authentication_ldap_configuration => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested authentication_ldap_configuration" do
      ldap_configuration = Authentication::LdapConfiguration.create! valid_attributes
      expect {
        delete :destroy, {:id => ldap_configuration.to_param}, valid_session
      }.to change(Authentication::LdapConfiguration, :count).by(-1)
    end

    it "redirects to the authentication_ldap_configurations list" do
      ldap_configuration = Authentication::LdapConfiguration.create! valid_attributes
      delete :destroy, {:id => ldap_configuration.to_param}, valid_session
      response.should redirect_to(authentication_ldap_configurations_url)
    end
  end

end
